version: 2

sources:
  - name: raw_data
    project: dbt-ecommerce-496202
    dataset: raw_data
    tables:
      - name: olist_orders_dataset
      - name: olist_customers_dataset
      - name: olist_order_payments_dataset
      - name: olist_order_items_dataset
      - name: olist_products_dataset